use SICORE
go

truncate table SICORE_INVENTARIO
go

select * from SICORE_INVENTARIO

truncate table SICORE_MOVIMIENTO_INVENTARIO
go

select * from SICORE_MOVIMIENTO_INVENTARIO
--
ALTER TABLE SICORE_CERTIFICADO
DROP CONSTRAINT FK_CERTIFICADO_idFormalizacion;

ALTER TABLE SICORE_CERTIFICADO
DROP CONSTRAINT FK_CERTIFICADO_idCotizacion;

truncate table SICORE_CERTIFICADO
go

select * from SICORE_CERTIFICADO
--
ALTER TABLE SICORE_FORMALIZACION
DROP CONSTRAINT FK_FACTURA_idCotizacion;

truncate table SICORE_FORMALIZACION
go

select * from SICORE_FORMALIZACION
--

ALTER TABLE SICORE_COTIZACION
DROP CONSTRAINT FK_COTIZACION_PROYECTO_idProyecto;

ALTER TABLE SICORE_COTIZACION
DROP CONSTRAINT FK_CLIENTE_idCliente;

truncate table SICORE_COTIZACION
go

select * from SICORE_COTIZACION
--
ALTER TABLE SICORE_CERTIFICADO
ADD CONSTRAINT FK_CERTIFICADO_idFormalizacion
FOREIGN KEY (idFormalizacion) REFERENCES SICORE_FORMALIZACION (idFormalizacion);

ALTER TABLE SICORE_CERTIFICADO
ADD CONSTRAINT FK_CERTIFICADO_idCotizacion
FOREIGN KEY (idCotizacion) REFERENCES SICORE_COTIZACION (idCotizacion);

ALTER TABLE SICORE_FORMALIZACION
ADD CONSTRAINT FK_FACTURA_idCotizacion
FOREIGN KEY (idCotizacion) REFERENCES SICORE_COTIZACION (idCotizacion);

ALTER TABLE SICORE_COTIZACION
ADD CONSTRAINT FK_CLIENTE_idCliente
FOREIGN KEY (idCliente) REFERENCES SICORE_CLIENTE(idCliente);

ALTER TABLE SICORE_COTIZACION
ADD CONSTRAINT FK_COTIZACION_PROYECTO_idProyecto
FOREIGN KEY (idProyecto) REFERENCES SICORE_PROYECTO(idProyecto);
--