USE [SICORE]
GO
INSERT [dbo].[SICORE_PARAMETROS] ([idParametro], [valor], [descripcion]) VALUES (1, N'30', N'Total de días naturales para resolución de una solicitud')
GO
INSERT [dbo].[SICORE_PARAMETROS] ([idParametro], [valor], [descripcion]) VALUES (2, N'10', N'Días hábiles para corregir inconsistencias del formulario de solicitud de crédito')
GO
INSERT [dbo].[SICORE_PARAMETROS] ([idParametro], [valor], [descripcion]) VALUES (3, N'1', N'Consecutivo para el número de solicitud y número de expediente')
GO
INSERT [dbo].[SICORE_PARAMETROS] ([idParametro], [valor], [descripcion]) VALUES (4, N'tipos de propietarios', N'Dueño, Arrendatario, Albacea')
GO
INSERT [dbo].[SICORE_PARAMETROS] ([idParametro], [valor], [descripcion]) VALUES (5, N'S', N'Activar Doble Factor (N-No | S-Sí)')
GO
INSERT [dbo].[SICORE_PARAMETROS] ([idParametro], [valor], [descripcion]) VALUES (6, N'local', N'servidor donde está instalado el sistema (desa ó scgi)')
GO
SET IDENTITY_INSERT [dbo].[SICORE_PERFIL] ON 
GO
INSERT [dbo].[SICORE_PERFIL] ([idPerfil], [nombre], [descripcion], [doCRUDUsuarios]) VALUES (1, N'CLlENTE', N'Usuario que registra la solicitud de crédito', N'N')
GO
INSERT [dbo].[SICORE_PERFIL] ([idPerfil], [nombre], [descripcion], [doCRUDUsuarios]) VALUES (2, N'DIRECTOR-DFF', N'Usuario Director de la Dirección de Fomento Forestal', N'S')
GO
INSERT [dbo].[SICORE_PERFIL] ([idPerfil], [nombre], [descripcion], [doCRUDUsuarios]) VALUES (3, N'JEFE-DGC', N'Usuario Jefe del Departamento de Gestión Crediticia', N'N')
GO
INSERT [dbo].[SICORE_PERFIL] ([idPerfil], [nombre], [descripcion], [doCRUDUsuarios]) VALUES (4, N'JEFE-DDF', N'Usuario Jefe del Departamento de Desarrollo Forestal', N'N')
GO
INSERT [dbo].[SICORE_PERFIL] ([idPerfil], [nombre], [descripcion], [doCRUDUsuarios]) VALUES (5, N'EJECUTIVO-DGC', N'Usuario Ejecutivo de crédito del Departamento de Gestión Crediticia', N'N')
GO
INSERT [dbo].[SICORE_PERFIL] ([idPerfil], [nombre], [descripcion], [doCRUDUsuarios]) VALUES (6, N'INGENIERO-DDF', N'Usuario Ingeniero Forestal del Departamento de Desarrollo Forestal', N'N')
GO
INSERT [dbo].[SICORE_PERFIL] ([idPerfil], [nombre], [descripcion], [doCRUDUsuarios]) VALUES (7, N'FIDEICOMISO', N'Usuario del FIDEICOMISO', N'N')
GO
INSERT [dbo].[SICORE_PERFIL] ([idPerfil], [nombre], [descripcion], [doCRUDUsuarios]) VALUES (8, N'FUNCIONARIO-DSA', N'Usuario de la Dirección de Servicios Ambientales (PSA-Monitoreo)', N'N')
GO
INSERT [dbo].[SICORE_PERFIL] ([idPerfil], [nombre], [descripcion], [doCRUDUsuarios]) VALUES (9, N'ASISTENTE', N'Usuario del Departamento de Gestión Crediticia responsable de recepción de solicitudes', N'N')
GO
INSERT [dbo].[SICORE_PERFIL] ([idPerfil], [nombre], [descripcion], [doCRUDUsuarios]) VALUES (10, N'UTIC', N'Usuario de UTIC para revisiones de funcionamiento', N'S')
GO
SET IDENTITY_INSERT [dbo].[SICORE_PERFIL] OFF
GO
INSERT [dbo].[SICORE_PERSONA] ([idPersona], [idTipoDocumentoID], [documentoID], [nombre], [primerApellido], [segundoApellido], [fechaNacimiento], [fechaCaducidadDocID], [idDistrito], [direccionExacta], [caserio], [idEstadoCivil], [apartadoPostal], [idGradoAcademico], [idProfesion], [indicadorGenero], [indicadorEstado], [aceptaSMS], [telefonoMovil], [telefonoFijoCasa], [telefonoFijoTrabajo], [fechaDefuncion], [indicadorFallecido], [correo], [idBanco], [cuentaIBAN], [certificadoIBAN], [numeroVersionAuditoria], [fechaInsertoAuditoria], [idUsuarioInsertoAuditoria], [fechaModificoAuditoria], [idUsuarioModificoAuditoria]) VALUES (430, 1, N'101900099', N'OMAR JORGE', N'RODRÍGUEZ', N'UMAÑA', CAST(N'1928-11-06T00:00:00.000' AS DateTime), NULL, 437, N'175 M AL ESTE DEL COLEGIO LA SALLE. SABANA SUR.', NULL, 3, NULL, 0, 30, N'M', N'A', N'N', N'77777777', NULL, NULL, NULL, N'N', N'temp@temp.com', 13, N'CR99999999999999999999', NULL, NULL, CAST(N'2023-11-27T08:02:01.037' AS DateTime), 3, NULL, NULL)
GO
INSERT [dbo].[SICORE_PERSONA] ([idPersona], [idTipoDocumentoID], [documentoID], [nombre], [primerApellido], [segundoApellido], [fechaNacimiento], [fechaCaducidadDocID], [idDistrito], [direccionExacta], [caserio], [idEstadoCivil], [apartadoPostal], [idGradoAcademico], [idProfesion], [indicadorGenero], [indicadorEstado], [aceptaSMS], [telefonoMovil], [telefonoFijoCasa], [telefonoFijoTrabajo], [fechaDefuncion], [indicadorFallecido], [correo], [idBanco], [cuentaIBAN], [certificadoIBAN], [numeroVersionAuditoria], [fechaInsertoAuditoria], [idUsuarioInsertoAuditoria], [fechaModificoAuditoria], [idUsuarioModificoAuditoria]) VALUES (1070, 1, N'101930024', N'IBO', N'CHACÓN', N'BADILLA', CAST(N'1929-03-02T00:00:00.000' AS DateTime), NULL, 409, N'100M N Y 50M O SODA LA ESQUINA POTRERO GRANDE, BUENOS AIRES', NULL, 3, NULL, 1, 5, N'M', N'A', N'S', N'85683378', N'83572140', N'', NULL, N'N', N'rochaconpz@gmail.com', NULL, NULL, NULL, NULL, CAST(N'2023-11-29T21:27:39.317' AS DateTime), 3, NULL, NULL)
GO
INSERT [dbo].[SICORE_PERSONA] ([idPersona], [idTipoDocumentoID], [documentoID], [nombre], [primerApellido], [segundoApellido], [fechaNacimiento], [fechaCaducidadDocID], [idDistrito], [direccionExacta], [caserio], [idEstadoCivil], [apartadoPostal], [idGradoAcademico], [idProfesion], [indicadorGenero], [indicadorEstado], [aceptaSMS], [telefonoMovil], [telefonoFijoCasa], [telefonoFijoTrabajo], [fechaDefuncion], [indicadorFallecido], [correo], [idBanco], [cuentaIBAN], [certificadoIBAN], [numeroVersionAuditoria], [fechaInsertoAuditoria], [idUsuarioInsertoAuditoria], [fechaModificoAuditoria], [idUsuarioModificoAuditoria]) VALUES (1665, 1, N'101950656', N'DAISY', N'CABRERA', N'ARIAS', CAST(N'1929-09-14T00:00:00.000' AS DateTime), NULL, 10497, N'N.A.', NULL, 0, NULL, 0, 0, N'F', N'A', N'N', N'88888888', NULL, NULL, NULL, N'N', N'TEMP@TEMP.COM', NULL, NULL, NULL, 1, CAST(N'2023-11-29T17:43:43.023' AS DateTime), 3, NULL, NULL)
GO
INSERT [dbo].[SICORE_PERSONA] ([idPersona], [idTipoDocumentoID], [documentoID], [nombre], [primerApellido], [segundoApellido], [fechaNacimiento], [fechaCaducidadDocID], [idDistrito], [direccionExacta], [caserio], [idEstadoCivil], [apartadoPostal], [idGradoAcademico], [idProfesion], [indicadorGenero], [indicadorEstado], [aceptaSMS], [telefonoMovil], [telefonoFijoCasa], [telefonoFijoTrabajo], [fechaDefuncion], [indicadorFallecido], [correo], [idBanco], [cuentaIBAN], [certificadoIBAN], [numeroVersionAuditoria], [fechaInsertoAuditoria], [idUsuarioInsertoAuditoria], [fechaModificoAuditoria], [idUsuarioModificoAuditoria]) VALUES (5337, 1, N'102090799', N'NELLY', N'BARRANTES', N'PORRAS', CAST(N'1931-05-14T00:00:00.000' AS DateTime), NULL, 106, N'N.A.', NULL, 1, NULL, 11, 10309, N'F', N'A', N'S', N'88888888', NULL, NULL, NULL, N'N', N'temp@temp.com', 1, N'CR22222222222222222222', NULL, NULL, CAST(N'2023-11-24T08:22:04.920' AS DateTime), 3, NULL, NULL)
GO
INSERT [dbo].[SICORE_PERSONA] ([idPersona], [idTipoDocumentoID], [documentoID], [nombre], [primerApellido], [segundoApellido], [fechaNacimiento], [fechaCaducidadDocID], [idDistrito], [direccionExacta], [caserio], [idEstadoCivil], [apartadoPostal], [idGradoAcademico], [idProfesion], [indicadorGenero], [indicadorEstado], [aceptaSMS], [telefonoMovil], [telefonoFijoCasa], [telefonoFijoTrabajo], [fechaDefuncion], [indicadorFallecido], [correo], [idBanco], [cuentaIBAN], [certificadoIBAN], [numeroVersionAuditoria], [fechaInsertoAuditoria], [idUsuarioInsertoAuditoria], [fechaModificoAuditoria], [idUsuarioModificoAuditoria]) VALUES (8026, 1, N'102180688', N'AMADO', N'NARANJO', N'ABARCA', CAST(N'1932-08-02T00:00:00.000' AS DateTime), NULL, 19, N'N.A.', NULL, 3, NULL, 9, 10428, N'M', N'A', N'S', N'88888888', N'22222222', NULL, NULL, N'N', N'naranjota1@gmail.com', 1, N'CR11111111111111111111', NULL, NULL, CAST(N'2023-11-29T14:31:40.327' AS DateTime), 3, CAST(N'2023-11-29T15:29:27.193' AS DateTime), NULL)
GO
INSERT [dbo].[SICORE_PERSONA] ([idPersona], [idTipoDocumentoID], [documentoID], [nombre], [primerApellido], [segundoApellido], [fechaNacimiento], [fechaCaducidadDocID], [idDistrito], [direccionExacta], [caserio], [idEstadoCivil], [apartadoPostal], [idGradoAcademico], [idProfesion], [indicadorGenero], [indicadorEstado], [aceptaSMS], [telefonoMovil], [telefonoFijoCasa], [telefonoFijoTrabajo], [fechaDefuncion], [indicadorFallecido], [correo], [idBanco], [cuentaIBAN], [certificadoIBAN], [numeroVersionAuditoria], [fechaInsertoAuditoria], [idUsuarioInsertoAuditoria], [fechaModificoAuditoria], [idUsuarioModificoAuditoria]) VALUES (8087, 1, N'102180872', N'JOSEFA', N'PARRA', N'BLANCO', CAST(N'1932-08-11T00:00:00.000' AS DateTime), NULL, 123, N'SJ, PZ, 50 S AUTOS VERAMA BARRIO STA CECILIA ', NULL, 3, NULL, 9, 211, N'F', N'A', N'N', N'88888888', N'27710424', NULL, NULL, N'N', N'temp@temp.com', NULL, NULL, NULL, NULL, CAST(N'2023-11-29T14:44:07.183' AS DateTime), 3, NULL, NULL)
GO
INSERT [dbo].[SICORE_PERSONA] ([idPersona], [idTipoDocumentoID], [documentoID], [nombre], [primerApellido], [segundoApellido], [fechaNacimiento], [fechaCaducidadDocID], [idDistrito], [direccionExacta], [caserio], [idEstadoCivil], [apartadoPostal], [idGradoAcademico], [idProfesion], [indicadorGenero], [indicadorEstado], [aceptaSMS], [telefonoMovil], [telefonoFijoCasa], [telefonoFijoTrabajo], [fechaDefuncion], [indicadorFallecido], [correo], [idBanco], [cuentaIBAN], [certificadoIBAN], [numeroVersionAuditoria], [fechaInsertoAuditoria], [idUsuarioInsertoAuditoria], [fechaModificoAuditoria], [idUsuarioModificoAuditoria]) VALUES (8126, 1, N'102180993', N'JOSE CARLOS', N'ARIAS', N'ARIAS', CAST(N'1932-09-14T00:00:00.000' AS DateTime), NULL, 15, N'SAN RAFAEL ABAJO DE DESAMPARADOS, SAN JOSÉ, DE MC DONALDS 350 MTS S, FRENTE A PANADERÍA BRUCE', NULL, 11, NULL, 13, 30, N'M', N'A', N'N', N'88888888', N'22757110', NULL, NULL, N'N', N'temp@temp.com', NULL, NULL, NULL, NULL, CAST(N'2023-11-24T08:25:14.400' AS DateTime), 3, NULL, NULL)
GO
INSERT [dbo].[SICORE_PERSONA] ([idPersona], [idTipoDocumentoID], [documentoID], [nombre], [primerApellido], [segundoApellido], [fechaNacimiento], [fechaCaducidadDocID], [idDistrito], [direccionExacta], [caserio], [idEstadoCivil], [apartadoPostal], [idGradoAcademico], [idProfesion], [indicadorGenero], [indicadorEstado], [aceptaSMS], [telefonoMovil], [telefonoFijoCasa], [telefonoFijoTrabajo], [fechaDefuncion], [indicadorFallecido], [correo], [idBanco], [cuentaIBAN], [certificadoIBAN], [numeroVersionAuditoria], [fechaInsertoAuditoria], [idUsuarioInsertoAuditoria], [fechaModificoAuditoria], [idUsuarioModificoAuditoria]) VALUES (8579, 1, N'102200387', N'CARLOS', N'AGUERO', N'QUIROS', CAST(N'1932-11-11T00:00:00.000' AS DateTime), NULL, 67, N'VISTA DE MAR SAN RAFAEL DE PLATANARES PZ SJ', NULL, 3, NULL, 1, 5, N'M', N'A', N'N', N'88888888', NULL, NULL, NULL, N'N', N'102200387@temporal.com', 8, N'CR33333333333333333333', NULL, NULL, CAST(N'2023-11-24T14:18:30.133' AS DateTime), 3, CAST(N'2023-11-27T08:04:52.197' AS DateTime), NULL)
GO
INSERT [dbo].[SICORE_PERSONA] ([idPersona], [idTipoDocumentoID], [documentoID], [nombre], [primerApellido], [segundoApellido], [fechaNacimiento], [fechaCaducidadDocID], [idDistrito], [direccionExacta], [caserio], [idEstadoCivil], [apartadoPostal], [idGradoAcademico], [idProfesion], [indicadorGenero], [indicadorEstado], [aceptaSMS], [telefonoMovil], [telefonoFijoCasa], [telefonoFijoTrabajo], [fechaDefuncion], [indicadorFallecido], [correo], [idBanco], [cuentaIBAN], [certificadoIBAN], [numeroVersionAuditoria], [fechaInsertoAuditoria], [idUsuarioInsertoAuditoria], [fechaModificoAuditoria], [idUsuarioModificoAuditoria]) VALUES (10938, 1, N'102270556', N'NYDIA', N'ECHANDI', N'QUIROS', CAST(N'1933-10-07T00:00:00.000' AS DateTime), NULL, 69, N'HACIENDA LA ISABEL, OROSÍ, PARAÍSO DE CARTAGO', NULL, 11, NULL, 8, 25, N'F', N'A', N'N', N'88888888', N'', N'', NULL, N'N', N'temp@temp.com', NULL, NULL, NULL, NULL, CAST(N'2023-11-29T21:34:54.867' AS DateTime), 3, NULL, NULL)
GO
INSERT [dbo].[SICORE_PERSONA] ([idPersona], [idTipoDocumentoID], [documentoID], [nombre], [primerApellido], [segundoApellido], [fechaNacimiento], [fechaCaducidadDocID], [idDistrito], [direccionExacta], [caserio], [idEstadoCivil], [apartadoPostal], [idGradoAcademico], [idProfesion], [indicadorGenero], [indicadorEstado], [aceptaSMS], [telefonoMovil], [telefonoFijoCasa], [telefonoFijoTrabajo], [fechaDefuncion], [indicadorFallecido], [correo], [idBanco], [cuentaIBAN], [certificadoIBAN], [numeroVersionAuditoria], [fechaInsertoAuditoria], [idUsuarioInsertoAuditoria], [fechaModificoAuditoria], [idUsuarioModificoAuditoria]) VALUES (10961, 1, N'102270614', N'MARIA ELENA', N'VALVERDE', N'CHINCHILLA', CAST(N'1933-10-07T00:00:00.000' AS DateTime), NULL, 101, N'CUIDADELA BLANCO DE LA PULPERÍA K DE OROS PÉREZ ZELEDÓN', NULL, 11, NULL, 9, 30, N'F', N'A', N'N', N'89988868', N'27710368', NULL, NULL, N'N', N'temp@temp.com', NULL, NULL, NULL, NULL, CAST(N'2023-11-29T15:31:15.300' AS DateTime), 3, NULL, NULL)
GO
INSERT [dbo].[SICORE_PERSONA] ([idPersona], [idTipoDocumentoID], [documentoID], [nombre], [primerApellido], [segundoApellido], [fechaNacimiento], [fechaCaducidadDocID], [idDistrito], [direccionExacta], [caserio], [idEstadoCivil], [apartadoPostal], [idGradoAcademico], [idProfesion], [indicadorGenero], [indicadorEstado], [aceptaSMS], [telefonoMovil], [telefonoFijoCasa], [telefonoFijoTrabajo], [fechaDefuncion], [indicadorFallecido], [correo], [idBanco], [cuentaIBAN], [certificadoIBAN], [numeroVersionAuditoria], [fechaInsertoAuditoria], [idUsuarioInsertoAuditoria], [fechaModificoAuditoria], [idUsuarioModificoAuditoria]) VALUES (10969, 1, N'102270645', N'MERCEDES', N'CASTILLO', N'LEON', CAST(N'1933-11-01T00:00:00.000' AS DateTime), NULL, 77, N'200 OESTE DE LA PULPERIA EL PAVERO JILGUERAL', NULL, 11, NULL, 0, 28, N'F', N'A', N'N', N'88888888', N'', N'', NULL, N'N', N'temp@temp.com', NULL, NULL, NULL, NULL, CAST(N'2023-11-29T22:17:34.223' AS DateTime), 3, NULL, NULL)
GO
INSERT [dbo].[SICORE_PERSONA] ([idPersona], [idTipoDocumentoID], [documentoID], [nombre], [primerApellido], [segundoApellido], [fechaNacimiento], [fechaCaducidadDocID], [idDistrito], [direccionExacta], [caserio], [idEstadoCivil], [apartadoPostal], [idGradoAcademico], [idProfesion], [indicadorGenero], [indicadorEstado], [aceptaSMS], [telefonoMovil], [telefonoFijoCasa], [telefonoFijoTrabajo], [fechaDefuncion], [indicadorFallecido], [correo], [idBanco], [cuentaIBAN], [certificadoIBAN], [numeroVersionAuditoria], [fechaInsertoAuditoria], [idUsuarioInsertoAuditoria], [fechaModificoAuditoria], [idUsuarioModificoAuditoria]) VALUES (11543, 1, N'102290310', N'ANTONIO', N'RUBI', N'ADANIS', CAST(N'1934-01-07T00:00:00.000' AS DateTime), NULL, 78, N'LA  PAVONA , TURRUBARES, SAN JOSÉ, 500 METROS SUROESTE DE LA ESCUELA DEL LUGAR', NULL, 11, NULL, 1, 150, N'F', N'A', N'N', N'85026608', NULL, NULL, NULL, N'N', N'olgarubijaco@gmail.com', 20, N'CR32323232323232323232', NULL, NULL, CAST(N'2023-11-29T21:59:40.250' AS DateTime), 3, CAST(N'2023-11-30T13:15:08.153' AS DateTime), NULL)
GO
INSERT [dbo].[SICORE_PERSONA] ([idPersona], [idTipoDocumentoID], [documentoID], [nombre], [primerApellido], [segundoApellido], [fechaNacimiento], [fechaCaducidadDocID], [idDistrito], [direccionExacta], [caserio], [idEstadoCivil], [apartadoPostal], [idGradoAcademico], [idProfesion], [indicadorGenero], [indicadorEstado], [aceptaSMS], [telefonoMovil], [telefonoFijoCasa], [telefonoFijoTrabajo], [fechaDefuncion], [indicadorFallecido], [correo], [idBanco], [cuentaIBAN], [certificadoIBAN], [numeroVersionAuditoria], [fechaInsertoAuditoria], [idUsuarioInsertoAuditoria], [fechaModificoAuditoria], [idUsuarioModificoAuditoria]) VALUES (12022, 1, N'102300730', N'EDWIN', N'MONGE', N'PADILLA', CAST(N'1934-02-13T00:00:00.000' AS DateTime), NULL, 68, N'test', NULL, 3, NULL, 1, 30, N'F', N'A', N'N', N'83592162', N'27710424', N'', NULL, N'N', N'temp@temp', NULL, NULL, NULL, NULL, CAST(N'2023-11-29T20:27:28.773' AS DateTime), 3, NULL, NULL)
GO
INSERT [dbo].[SICORE_PERSONA] ([idPersona], [idTipoDocumentoID], [documentoID], [nombre], [primerApellido], [segundoApellido], [fechaNacimiento], [fechaCaducidadDocID], [idDistrito], [direccionExacta], [caserio], [idEstadoCivil], [apartadoPostal], [idGradoAcademico], [idProfesion], [indicadorGenero], [indicadorEstado], [aceptaSMS], [telefonoMovil], [telefonoFijoCasa], [telefonoFijoTrabajo], [fechaDefuncion], [indicadorFallecido], [correo], [idBanco], [cuentaIBAN], [certificadoIBAN], [numeroVersionAuditoria], [fechaInsertoAuditoria], [idUsuarioInsertoAuditoria], [fechaModificoAuditoria], [idUsuarioModificoAuditoria]) VALUES (15225, 1, N'102390374', N'ROSIBEL', N'CASTRO', N'GARCIA', CAST(N'1935-05-28T00:00:00.000' AS DateTime), NULL, 78, N'CALLLE 37 Y 39, AVENIDA 15, BARRIO ESCALANTE, SAN JOSE', NULL, 3, NULL, 0, 28, N'F', N'A', N'N', N'88888888', N'', N'', NULL, N'N', N'temp@temp.com', NULL, NULL, NULL, NULL, CAST(N'2023-11-29T22:01:02.620' AS DateTime), 3, NULL, NULL)
GO
INSERT [dbo].[SICORE_PERSONA] ([idPersona], [idTipoDocumentoID], [documentoID], [nombre], [primerApellido], [segundoApellido], [fechaNacimiento], [fechaCaducidadDocID], [idDistrito], [direccionExacta], [caserio], [idEstadoCivil], [apartadoPostal], [idGradoAcademico], [idProfesion], [indicadorGenero], [indicadorEstado], [aceptaSMS], [telefonoMovil], [telefonoFijoCasa], [telefonoFijoTrabajo], [fechaDefuncion], [indicadorFallecido], [correo], [idBanco], [cuentaIBAN], [certificadoIBAN], [numeroVersionAuditoria], [fechaInsertoAuditoria], [idUsuarioInsertoAuditoria], [fechaModificoAuditoria], [idUsuarioModificoAuditoria]) VALUES (17943, 1, N'102460375', N'GONZALO', N'ROJAS', N'ALVARADO', CAST(N'1936-04-19T00:00:00.000' AS DateTime), NULL, 67, N'BRUJO DE RIO NUEVO', NULL, 3, NULL, 0, 5, N'M', N'A', N'N', N'88888888', NULL, NULL, NULL, N'N', N'temp@temp.com', 2, NULL, NULL, 1, CAST(N'2023-12-07T10:08:35.047' AS DateTime), 3, NULL, NULL)
GO
INSERT [dbo].[SICORE_PERSONA] ([idPersona], [idTipoDocumentoID], [documentoID], [nombre], [primerApellido], [segundoApellido], [fechaNacimiento], [fechaCaducidadDocID], [idDistrito], [direccionExacta], [caserio], [idEstadoCivil], [apartadoPostal], [idGradoAcademico], [idProfesion], [indicadorGenero], [indicadorEstado], [aceptaSMS], [telefonoMovil], [telefonoFijoCasa], [telefonoFijoTrabajo], [fechaDefuncion], [indicadorFallecido], [correo], [idBanco], [cuentaIBAN], [certificadoIBAN], [numeroVersionAuditoria], [fechaInsertoAuditoria], [idUsuarioInsertoAuditoria], [fechaModificoAuditoria], [idUsuarioModificoAuditoria]) VALUES (18718, 1, N'102480241', N'JOSE ANGEL', N'MARIN', N'ESPINOZA', CAST(N'1936-06-01T00:00:00.000' AS DateTime), NULL, 110, N'1 km este de la Escuela de San Carlos', NULL, 3, NULL, 7, 150, N'M', N'A', N'S', N'84163814', N'84163814', NULL, NULL, N'N', N'freroqui14@gmail.com', NULL, NULL, NULL, 1, CAST(N'2023-12-07T10:09:44.597' AS DateTime), 3, NULL, NULL)
GO
INSERT [dbo].[SICORE_PERSONA] ([idPersona], [idTipoDocumentoID], [documentoID], [nombre], [primerApellido], [segundoApellido], [fechaNacimiento], [fechaCaducidadDocID], [idDistrito], [direccionExacta], [caserio], [idEstadoCivil], [apartadoPostal], [idGradoAcademico], [idProfesion], [indicadorGenero], [indicadorEstado], [aceptaSMS], [telefonoMovil], [telefonoFijoCasa], [telefonoFijoTrabajo], [fechaDefuncion], [indicadorFallecido], [correo], [idBanco], [cuentaIBAN], [certificadoIBAN], [numeroVersionAuditoria], [fechaInsertoAuditoria], [idUsuarioInsertoAuditoria], [fechaModificoAuditoria], [idUsuarioModificoAuditoria]) VALUES (19069, 1, N'102490102', N'NOILI', N'ALVAREZ', N'PERAZA', CAST(N'1936-07-19T00:00:00.000' AS DateTime), NULL, 68, N'SAN JOSÉ, MORAVIA, SAN VICENTE, COSTADO OESTE DEL ESTACIONAMIENTO DE PEQUEÑO MUNDO, CASA CON PORTÓN DE MADERA', NULL, 11, NULL, 7, 10340, N'F', N'A', N'N', N'88888888', N'22416926', NULL, NULL, N'N', N'ni@ni.com', NULL, NULL, NULL, 14, CAST(N'2023-11-29T16:34:57.877' AS DateTime), 3, NULL, NULL)
GO
INSERT [dbo].[SICORE_PERSONA] ([idPersona], [idTipoDocumentoID], [documentoID], [nombre], [primerApellido], [segundoApellido], [fechaNacimiento], [fechaCaducidadDocID], [idDistrito], [direccionExacta], [caserio], [idEstadoCivil], [apartadoPostal], [idGradoAcademico], [idProfesion], [indicadorGenero], [indicadorEstado], [aceptaSMS], [telefonoMovil], [telefonoFijoCasa], [telefonoFijoTrabajo], [fechaDefuncion], [indicadorFallecido], [correo], [idBanco], [cuentaIBAN], [certificadoIBAN], [numeroVersionAuditoria], [fechaInsertoAuditoria], [idUsuarioInsertoAuditoria], [fechaModificoAuditoria], [idUsuarioModificoAuditoria]) VALUES (19072, 1, N'102490117', N'MARCO AURELIO', N'MADRIZ', N'DE MEZERVILLE', CAST(N'1936-05-16T00:00:00.000' AS DateTime), NULL, 76, N'URBANIZACION MONTEALEGRE, CALLE, 29, CASA 24, ZAPOTE, SAN JOSE', NULL, 7, NULL, 0, 17, N'M', N'A', N'N', N'88888888', NULL, NULL, NULL, N'N', N'temp@temp.com', NULL, NULL, NULL, 1, CAST(N'2023-12-05T13:34:48.737' AS DateTime), 3, NULL, NULL)
GO
INSERT [dbo].[SICORE_PERSONA] ([idPersona], [idTipoDocumentoID], [documentoID], [nombre], [primerApellido], [segundoApellido], [fechaNacimiento], [fechaCaducidadDocID], [idDistrito], [direccionExacta], [caserio], [idEstadoCivil], [apartadoPostal], [idGradoAcademico], [idProfesion], [indicadorGenero], [indicadorEstado], [aceptaSMS], [telefonoMovil], [telefonoFijoCasa], [telefonoFijoTrabajo], [fechaDefuncion], [indicadorFallecido], [correo], [idBanco], [cuentaIBAN], [certificadoIBAN], [numeroVersionAuditoria], [fechaInsertoAuditoria], [idUsuarioInsertoAuditoria], [fechaModificoAuditoria], [idUsuarioModificoAuditoria]) VALUES (19310, 1, N'102490684', N'MARGARITA', N'SOLANO', N'SOLANO', CAST(N'1936-08-16T00:00:00.000' AS DateTime), NULL, 67, N'SJ, URUCA, BARRO EL ROBLEDAL CASA M45', NULL, 11, NULL, 2, 27, N'F', N'A', N'N', N'87075405', N'22901354', NULL, NULL, N'N', N'josepablo3520@yahoo.com', NULL, NULL, NULL, 2, CAST(N'2023-11-30T13:15:47.890' AS DateTime), 3, NULL, NULL)
GO
INSERT [dbo].[SICORE_PERSONA] ([idPersona], [idTipoDocumentoID], [documentoID], [nombre], [primerApellido], [segundoApellido], [fechaNacimiento], [fechaCaducidadDocID], [idDistrito], [direccionExacta], [caserio], [idEstadoCivil], [apartadoPostal], [idGradoAcademico], [idProfesion], [indicadorGenero], [indicadorEstado], [aceptaSMS], [telefonoMovil], [telefonoFijoCasa], [telefonoFijoTrabajo], [fechaDefuncion], [indicadorFallecido], [correo], [idBanco], [cuentaIBAN], [certificadoIBAN], [numeroVersionAuditoria], [fechaInsertoAuditoria], [idUsuarioInsertoAuditoria], [fechaModificoAuditoria], [idUsuarioModificoAuditoria]) VALUES (23570, 1, N'102590705', N'ELPIDIO', N'HERNÁNDEZ', N'PORRAS', CAST(N'1900-01-01T00:00:00.000' AS DateTime), NULL, 15, N'GUADALUPE DE TARRAZÚ, CALLE VIEJA DE GUADALUPE 1 KM S DE LA ESCUELA', NULL, 11, NULL, 2, 5, N'M', N'A', N'N', N'88888888', N'25464001', NULL, NULL, N'N', N'centroagricoladota@gmail.com', 20, N'CR45454545454444444444', NULL, NULL, CAST(N'2023-11-27T08:45:51.727' AS DateTime), 3, NULL, NULL)
GO
INSERT [dbo].[SICORE_PERSONA] ([idPersona], [idTipoDocumentoID], [documentoID], [nombre], [primerApellido], [segundoApellido], [fechaNacimiento], [fechaCaducidadDocID], [idDistrito], [direccionExacta], [caserio], [idEstadoCivil], [apartadoPostal], [idGradoAcademico], [idProfesion], [indicadorGenero], [indicadorEstado], [aceptaSMS], [telefonoMovil], [telefonoFijoCasa], [telefonoFijoTrabajo], [fechaDefuncion], [indicadorFallecido], [correo], [idBanco], [cuentaIBAN], [certificadoIBAN], [numeroVersionAuditoria], [fechaInsertoAuditoria], [idUsuarioInsertoAuditoria], [fechaModificoAuditoria], [idUsuarioModificoAuditoria]) VALUES (24445, 1, N'102610514', N'JOSE ANTONIO', N'MONGE', N'MENA', CAST(N'1938-01-07T00:00:00.000' AS DateTime), NULL, 316, N'EL JARDÍN, PÁRAMO, PEREZ ZELEDÓN, SAN JOSÉ, 800 M S DE LA ESCUELA EL JARDÍN', NULL, 3, NULL, 1, 150, N'M', N'A', N'S', N'89889078', N'22211546', N'', NULL, N'N', N'lmongev@yahoo.com', NULL, NULL, NULL, NULL, CAST(N'2023-11-27T08:48:26.057' AS DateTime), 3, NULL, NULL)
GO
INSERT [dbo].[SICORE_PERSONA] ([idPersona], [idTipoDocumentoID], [documentoID], [nombre], [primerApellido], [segundoApellido], [fechaNacimiento], [fechaCaducidadDocID], [idDistrito], [direccionExacta], [caserio], [idEstadoCivil], [apartadoPostal], [idGradoAcademico], [idProfesion], [indicadorGenero], [indicadorEstado], [aceptaSMS], [telefonoMovil], [telefonoFijoCasa], [telefonoFijoTrabajo], [fechaDefuncion], [indicadorFallecido], [correo], [idBanco], [cuentaIBAN], [certificadoIBAN], [numeroVersionAuditoria], [fechaInsertoAuditoria], [idUsuarioInsertoAuditoria], [fechaModificoAuditoria], [idUsuarioModificoAuditoria]) VALUES (24648, 1, N'102610943', N'RAMONA', N'ANGULO', N'PÉREZ', CAST(N'1938-03-11T00:00:00.000' AS DateTime), NULL, 78, N'BARRIO ALEMANIA N°4367, PALMAR NORTE, OSA', NULL, 11, NULL, 1, 28, N'F', N'A', N'N', N'88241377', N'', N'', NULL, N'N', N'mariocam65@gmail.com', NULL, NULL, NULL, NULL, CAST(N'2023-11-29T21:49:21.497' AS DateTime), 3, NULL, NULL)
GO
INSERT [dbo].[SICORE_PERSONA] ([idPersona], [idTipoDocumentoID], [documentoID], [nombre], [primerApellido], [segundoApellido], [fechaNacimiento], [fechaCaducidadDocID], [idDistrito], [direccionExacta], [caserio], [idEstadoCivil], [apartadoPostal], [idGradoAcademico], [idProfesion], [indicadorGenero], [indicadorEstado], [aceptaSMS], [telefonoMovil], [telefonoFijoCasa], [telefonoFijoTrabajo], [fechaDefuncion], [indicadorFallecido], [correo], [idBanco], [cuentaIBAN], [certificadoIBAN], [numeroVersionAuditoria], [fechaInsertoAuditoria], [idUsuarioInsertoAuditoria], [fechaModificoAuditoria], [idUsuarioModificoAuditoria]) VALUES (26689, 1, N'102660472', N'JUAN LEONARDO', N'MENA', N'PARRA', CAST(N'1938-07-17T00:00:00.000' AS DateTime), NULL, 77, N'200 MTS ESTE DE LA PLAZA DE DEPORTES  DE POLKA ,CANDELARITA', NULL, 1, NULL, 1, 150, N'F', N'A', N'N', N'88888888', N'24165728', NULL, NULL, N'N', N'coopepuris@racsa.co.cr', 1, N'CR33333333333333333333', NULL, 1, CAST(N'2023-12-04T14:13:31.290' AS DateTime), 3, NULL, NULL)
GO
INSERT [dbo].[SICORE_PERSONA] ([idPersona], [idTipoDocumentoID], [documentoID], [nombre], [primerApellido], [segundoApellido], [fechaNacimiento], [fechaCaducidadDocID], [idDistrito], [direccionExacta], [caserio], [idEstadoCivil], [apartadoPostal], [idGradoAcademico], [idProfesion], [indicadorGenero], [indicadorEstado], [aceptaSMS], [telefonoMovil], [telefonoFijoCasa], [telefonoFijoTrabajo], [fechaDefuncion], [indicadorFallecido], [correo], [idBanco], [cuentaIBAN], [certificadoIBAN], [numeroVersionAuditoria], [fechaInsertoAuditoria], [idUsuarioInsertoAuditoria], [fechaModificoAuditoria], [idUsuarioModificoAuditoria]) VALUES (31035, 1, N'102760109', N'EMILCE', N'AGUILAR', N'VARGAS', CAST(N'1939-02-12T00:00:00.000' AS DateTime), NULL, 67, N'N.A.', NULL, 0, NULL, 0, 0, N'F', N'A', N'N', N'88888888', N'', N'', NULL, N'N', N'temp@temp.com', NULL, NULL, NULL, NULL, CAST(N'2023-12-05T17:20:57.107' AS DateTime), 3, NULL, NULL)
GO
INSERT [dbo].[SICORE_PERSONA] ([idPersona], [idTipoDocumentoID], [documentoID], [nombre], [primerApellido], [segundoApellido], [fechaNacimiento], [fechaCaducidadDocID], [idDistrito], [direccionExacta], [caserio], [idEstadoCivil], [apartadoPostal], [idGradoAcademico], [idProfesion], [indicadorGenero], [indicadorEstado], [aceptaSMS], [telefonoMovil], [telefonoFijoCasa], [telefonoFijoTrabajo], [fechaDefuncion], [indicadorFallecido], [correo], [idBanco], [cuentaIBAN], [certificadoIBAN], [numeroVersionAuditoria], [fechaInsertoAuditoria], [idUsuarioInsertoAuditoria], [fechaModificoAuditoria], [idUsuarioModificoAuditoria]) VALUES (31644, 1, N'102770498', N'LILLY', N'JIMÉNEZ', N'PIEDRA', CAST(N'1939-05-08T00:00:00.000' AS DateTime), NULL, 40, N' ASERRÍ CENTRO, URBANIZACIÓN LAS TRES MARÍAS, CASA N°91', NULL, 11, NULL, 1, 28, N'F', N'A', N'S', N'85678315', N'22303137', N'', NULL, N'N', N'minormarin09@gmail.com', NULL, NULL, NULL, NULL, CAST(N'2023-12-05T17:21:33.223' AS DateTime), 3, NULL, NULL)
GO
INSERT [dbo].[SICORE_PERSONA] ([idPersona], [idTipoDocumentoID], [documentoID], [nombre], [primerApellido], [segundoApellido], [fechaNacimiento], [fechaCaducidadDocID], [idDistrito], [direccionExacta], [caserio], [idEstadoCivil], [apartadoPostal], [idGradoAcademico], [idProfesion], [indicadorGenero], [indicadorEstado], [aceptaSMS], [telefonoMovil], [telefonoFijoCasa], [telefonoFijoTrabajo], [fechaDefuncion], [indicadorFallecido], [correo], [idBanco], [cuentaIBAN], [certificadoIBAN], [numeroVersionAuditoria], [fechaInsertoAuditoria], [idUsuarioInsertoAuditoria], [fechaModificoAuditoria], [idUsuarioModificoAuditoria]) VALUES (34055, 1, N'102820902', N'ABDON', N'ABARCA', N'PORTUGUEZ', CAST(N'1939-11-26T00:00:00.000' AS DateTime), NULL, 67, N'50 M ESTE DE LA IGLESIA CATOLICA DE LLANO BONITO, LEON CORTEZ', NULL, 3, NULL, 0, 5, N'M', N'A', N'N', N'77777777', N'', N'', NULL, N'N', N'temp@temp.com', NULL, NULL, NULL, NULL, CAST(N'2023-12-05T17:22:16.147' AS DateTime), 3, NULL, NULL)
GO
INSERT [dbo].[SICORE_PERSONA] ([idPersona], [idTipoDocumentoID], [documentoID], [nombre], [primerApellido], [segundoApellido], [fechaNacimiento], [fechaCaducidadDocID], [idDistrito], [direccionExacta], [caserio], [idEstadoCivil], [apartadoPostal], [idGradoAcademico], [idProfesion], [indicadorGenero], [indicadorEstado], [aceptaSMS], [telefonoMovil], [telefonoFijoCasa], [telefonoFijoTrabajo], [fechaDefuncion], [indicadorFallecido], [correo], [idBanco], [cuentaIBAN], [certificadoIBAN], [numeroVersionAuditoria], [fechaInsertoAuditoria], [idUsuarioInsertoAuditoria], [fechaModificoAuditoria], [idUsuarioModificoAuditoria]) VALUES (50416, 1, N'103140495', N'BOLIVAR', N'GARCIA', N'DÍAZ', CAST(N'1944-02-05T00:00:00.000' AS DateTime), NULL, 76, N'CRUCE AMASTATAL CHIRES PURISCAL', NULL, 3, NULL, 0, 5, N'M', N'A', N'N', N'84848484', NULL, NULL, NULL, N'N', N'TEMP@TEMP.COM', NULL, NULL, NULL, NULL, CAST(N'2023-11-24T15:38:41.297' AS DateTime), 3, NULL, NULL)
GO
INSERT [dbo].[SICORE_PERSONA] ([idPersona], [idTipoDocumentoID], [documentoID], [nombre], [primerApellido], [segundoApellido], [fechaNacimiento], [fechaCaducidadDocID], [idDistrito], [direccionExacta], [caserio], [idEstadoCivil], [apartadoPostal], [idGradoAcademico], [idProfesion], [indicadorGenero], [indicadorEstado], [aceptaSMS], [telefonoMovil], [telefonoFijoCasa], [telefonoFijoTrabajo], [fechaDefuncion], [indicadorFallecido], [correo], [idBanco], [cuentaIBAN], [certificadoIBAN], [numeroVersionAuditoria], [fechaInsertoAuditoria], [idUsuarioInsertoAuditoria], [fechaModificoAuditoria], [idUsuarioModificoAuditoria]) VALUES (52735, 1, N'103180617', N'MARIA ELENA', N'FALLAS', N'MATA', CAST(N'1944-02-17T00:00:00.000' AS DateTime), NULL, 78, N'PEREZ ZELEDON, BARRIO LOS PINOS, DE LA PULPERIA LAS PALMAS 50 M SUR', NULL, 7, NULL, 1, 28, N'F', N'A', N'N', N'88241377', NULL, NULL, NULL, N'N', N'mariocam65@gmail.com', NULL, NULL, NULL, 1, CAST(N'2023-11-29T14:48:09.023' AS DateTime), 3, NULL, NULL)
GO
INSERT [dbo].[SICORE_PERSONA] ([idPersona], [idTipoDocumentoID], [documentoID], [nombre], [primerApellido], [segundoApellido], [fechaNacimiento], [fechaCaducidadDocID], [idDistrito], [direccionExacta], [caserio], [idEstadoCivil], [apartadoPostal], [idGradoAcademico], [idProfesion], [indicadorGenero], [indicadorEstado], [aceptaSMS], [telefonoMovil], [telefonoFijoCasa], [telefonoFijoTrabajo], [fechaDefuncion], [indicadorFallecido], [correo], [idBanco], [cuentaIBAN], [certificadoIBAN], [numeroVersionAuditoria], [fechaInsertoAuditoria], [idUsuarioInsertoAuditoria], [fechaModificoAuditoria], [idUsuarioModificoAuditoria]) VALUES (59658, 1, N'103300172', N'NORMAN', N'MONTES', N'BADILLA', CAST(N'1900-01-01T00:00:00.000' AS DateTime), NULL, 252, N'Casa 8, Barrio Holandés, San Ramón, La unión Cartago.', N'', 3, NULL, 7, 3, N'M', N'A', N'N', N'88775442', N'27113089', NULL, NULL, N'N', N'afernandez@repacla.com', NULL, NULL, NULL, 1, CAST(N'2023-12-04T14:17:25.567' AS DateTime), 3, NULL, NULL)
GO
INSERT [dbo].[SICORE_PERSONA] ([idPersona], [idTipoDocumentoID], [documentoID], [nombre], [primerApellido], [segundoApellido], [fechaNacimiento], [fechaCaducidadDocID], [idDistrito], [direccionExacta], [caserio], [idEstadoCivil], [apartadoPostal], [idGradoAcademico], [idProfesion], [indicadorGenero], [indicadorEstado], [aceptaSMS], [telefonoMovil], [telefonoFijoCasa], [telefonoFijoTrabajo], [fechaDefuncion], [indicadorFallecido], [correo], [idBanco], [cuentaIBAN], [certificadoIBAN], [numeroVersionAuditoria], [fechaInsertoAuditoria], [idUsuarioInsertoAuditoria], [fechaModificoAuditoria], [idUsuarioModificoAuditoria]) VALUES (235924, 1, N'105610337', N'RONNY STANLEY', N'MUÑOZ', N'SALAZAR', CAST(N'1961-07-27T00:00:00.000' AS DateTime), NULL, 15, N'N.A.', NULL, 0, NULL, 0, 0, N'M', N'A', N'N', N'83313963', NULL, NULL, NULL, N'N', N'temp@tmp.tmp', NULL, NULL, NULL, NULL, CAST(N'2023-11-27T10:33:43.677' AS DateTime), 27, NULL, NULL)
GO
INSERT [dbo].[SICORE_PERSONA] ([idPersona], [idTipoDocumentoID], [documentoID], [nombre], [primerApellido], [segundoApellido], [fechaNacimiento], [fechaCaducidadDocID], [idDistrito], [direccionExacta], [caserio], [idEstadoCivil], [apartadoPostal], [idGradoAcademico], [idProfesion], [indicadorGenero], [indicadorEstado], [aceptaSMS], [telefonoMovil], [telefonoFijoCasa], [telefonoFijoTrabajo], [fechaDefuncion], [indicadorFallecido], [correo], [idBanco], [cuentaIBAN], [certificadoIBAN], [numeroVersionAuditoria], [fechaInsertoAuditoria], [idUsuarioInsertoAuditoria], [fechaModificoAuditoria], [idUsuarioModificoAuditoria]) VALUES (479673, 1, N'108500854', N'ANA YANCI', N'MARCHENA', N'DURAN', CAST(N'2000-12-29T00:00:00.000' AS DateTime), NULL, 78, N'N.A.', NULL, 1, NULL, 1, 156, N'F', N'A', N'S', N'85875855', N'85858855', NULL, NULL, N'N', N'anayan@temp.tmp', 6, N'CR52122222222222222222', NULL, NULL, CAST(N'2023-11-28T09:55:40.307' AS DateTime), 27, CAST(N'2023-11-28T09:56:28.820' AS DateTime), NULL)
GO
INSERT [dbo].[SICORE_PERSONA] ([idPersona], [idTipoDocumentoID], [documentoID], [nombre], [primerApellido], [segundoApellido], [fechaNacimiento], [fechaCaducidadDocID], [idDistrito], [direccionExacta], [caserio], [idEstadoCivil], [apartadoPostal], [idGradoAcademico], [idProfesion], [indicadorGenero], [indicadorEstado], [aceptaSMS], [telefonoMovil], [telefonoFijoCasa], [telefonoFijoTrabajo], [fechaDefuncion], [indicadorFallecido], [correo], [idBanco], [cuentaIBAN], [certificadoIBAN], [numeroVersionAuditoria], [fechaInsertoAuditoria], [idUsuarioInsertoAuditoria], [fechaModificoAuditoria], [idUsuarioModificoAuditoria]) VALUES (481338, 1, N'108520741', N'MANUEL ALBERTO', N'ZUÑIGA', N'ALVARADO', CAST(N'1900-01-01T00:00:00.000' AS DateTime), NULL, 78, N'N.A.', NULL, 1, NULL, 1, 10447, N'M', N'A', N'N', N'85858585', N'85858585', NULL, NULL, N'N', N'manuel@tmp.tom', 6, N'CR52545254525452555555', NULL, NULL, CAST(N'2023-11-28T10:35:42.520' AS DateTime), 3, NULL, NULL)
GO
INSERT [dbo].[SICORE_PERSONA] ([idPersona], [idTipoDocumentoID], [documentoID], [nombre], [primerApellido], [segundoApellido], [fechaNacimiento], [fechaCaducidadDocID], [idDistrito], [direccionExacta], [caserio], [idEstadoCivil], [apartadoPostal], [idGradoAcademico], [idProfesion], [indicadorGenero], [indicadorEstado], [aceptaSMS], [telefonoMovil], [telefonoFijoCasa], [telefonoFijoTrabajo], [fechaDefuncion], [indicadorFallecido], [correo], [idBanco], [cuentaIBAN], [certificadoIBAN], [numeroVersionAuditoria], [fechaInsertoAuditoria], [idUsuarioInsertoAuditoria], [fechaModificoAuditoria], [idUsuarioModificoAuditoria]) VALUES (555239, 1, N'109360935', N'CHRISTIAN', N'DÍAZ', N'QUESADA', CAST(N'1976-05-07T00:00:00.000' AS DateTime), NULL, 0, NULL, NULL, 0, NULL, 0, 0, N'M', N'A', NULL, N'87589654', NULL, NULL, NULL, NULL, N'cristiandiazcliente@temp.temp', NULL, NULL, NULL, 1, CAST(N'2023-11-17T10:48:49.620' AS DateTime), 25, CAST(N'2023-11-17T10:48:49.620' AS DateTime), 25)
GO
INSERT [dbo].[SICORE_PERSONA] ([idPersona], [idTipoDocumentoID], [documentoID], [nombre], [primerApellido], [segundoApellido], [fechaNacimiento], [fechaCaducidadDocID], [idDistrito], [direccionExacta], [caserio], [idEstadoCivil], [apartadoPostal], [idGradoAcademico], [idProfesion], [indicadorGenero], [indicadorEstado], [aceptaSMS], [telefonoMovil], [telefonoFijoCasa], [telefonoFijoTrabajo], [fechaDefuncion], [indicadorFallecido], [correo], [idBanco], [cuentaIBAN], [certificadoIBAN], [numeroVersionAuditoria], [fechaInsertoAuditoria], [idUsuarioInsertoAuditoria], [fechaModificoAuditoria], [idUsuarioModificoAuditoria]) VALUES (579225, 1, N'109630852', N'JAIRO JORGE', N'BRENES', N'OVIEDO', CAST(N'1900-01-01T00:00:00.000' AS DateTime), NULL, 121, N'N.A.', NULL, 2, NULL, 3, 10375, N'M', N'A', N'N', N'74859685', N'74859685', NULL, NULL, N'N', N'jairo@temp.tmp', NULL, NULL, NULL, NULL, CAST(N'2023-11-28T10:36:55.100' AS DateTime), 3, NULL, NULL)
GO
INSERT [dbo].[SICORE_PERSONA] ([idPersona], [idTipoDocumentoID], [documentoID], [nombre], [primerApellido], [segundoApellido], [fechaNacimiento], [fechaCaducidadDocID], [idDistrito], [direccionExacta], [caserio], [idEstadoCivil], [apartadoPostal], [idGradoAcademico], [idProfesion], [indicadorGenero], [indicadorEstado], [aceptaSMS], [telefonoMovil], [telefonoFijoCasa], [telefonoFijoTrabajo], [fechaDefuncion], [indicadorFallecido], [correo], [idBanco], [cuentaIBAN], [certificadoIBAN], [numeroVersionAuditoria], [fechaInsertoAuditoria], [idUsuarioInsertoAuditoria], [fechaModificoAuditoria], [idUsuarioModificoAuditoria]) VALUES (587168, 1, N'109720775', N'LIGIA', N'ZUÑIGA', N'LÓPEZ', CAST(N'1977-06-24T00:00:00.000' AS DateTime), NULL, 100, N'N.A.', NULL, 0, NULL, 0, 0, N'F', N'A', N'N', N'88888888', NULL, NULL, NULL, N'N', N'ligia.zuniga@fonafifo.go.cr', 7, N'CR08015103620025469800', NULL, NULL, CAST(N'2023-11-27T10:08:06.627' AS DateTime), 27, NULL, NULL)
GO
INSERT [dbo].[SICORE_PERSONA] ([idPersona], [idTipoDocumentoID], [documentoID], [nombre], [primerApellido], [segundoApellido], [fechaNacimiento], [fechaCaducidadDocID], [idDistrito], [direccionExacta], [caserio], [idEstadoCivil], [apartadoPostal], [idGradoAcademico], [idProfesion], [indicadorGenero], [indicadorEstado], [aceptaSMS], [telefonoMovil], [telefonoFijoCasa], [telefonoFijoTrabajo], [fechaDefuncion], [indicadorFallecido], [correo], [idBanco], [cuentaIBAN], [certificadoIBAN], [numeroVersionAuditoria], [fechaInsertoAuditoria], [idUsuarioInsertoAuditoria], [fechaModificoAuditoria], [idUsuarioModificoAuditoria]) VALUES (1749658, 1, N'301370726', N'ARNOLDO', N'SOLANO', N'ORTEGA', CAST(N'1939-01-01T00:00:00.000' AS DateTime), NULL, 258, N'N.A.', NULL, 3, NULL, 7, 220, N'M', N'A', N'N', N'88326878', N'25312454', NULL, NULL, N'N', N'aroldo@ortega.com', 2, N'CR12345678978545454545', NULL, 0, CAST(N'2024-02-26T15:15:02.613' AS DateTime), 6, NULL, NULL)
GO
INSERT [dbo].[SICORE_PERSONA] ([idPersona], [idTipoDocumentoID], [documentoID], [nombre], [primerApellido], [segundoApellido], [fechaNacimiento], [fechaCaducidadDocID], [idDistrito], [direccionExacta], [caserio], [idEstadoCivil], [apartadoPostal], [idGradoAcademico], [idProfesion], [indicadorGenero], [indicadorEstado], [aceptaSMS], [telefonoMovil], [telefonoFijoCasa], [telefonoFijoTrabajo], [fechaDefuncion], [indicadorFallecido], [correo], [idBanco], [cuentaIBAN], [certificadoIBAN], [numeroVersionAuditoria], [fechaInsertoAuditoria], [idUsuarioInsertoAuditoria], [fechaModificoAuditoria], [idUsuarioModificoAuditoria]) VALUES (1909116, 1, N'303450963', N'ROGELIO', N'SOLANO', N'ALVARADO', CAST(N'1977-02-01T00:00:00.000' AS DateTime), NULL, 100, N'N/A', NULL, 3, NULL, 12, 10483, N'M', N'A', N'S', N'87858785', N'', N'', NULL, N'N', N'rogelio.solano@fonafifo.go.cr', 20, N'CR12345678985452215522', NULL, NULL, CAST(N'2023-12-08T11:59:33.043' AS DateTime), 3, CAST(N'2023-12-08T13:18:06.517' AS DateTime), NULL)
GO
INSERT [dbo].[SICORE_PERSONA] ([idPersona], [idTipoDocumentoID], [documentoID], [nombre], [primerApellido], [segundoApellido], [fechaNacimiento], [fechaCaducidadDocID], [idDistrito], [direccionExacta], [caserio], [idEstadoCivil], [apartadoPostal], [idGradoAcademico], [idProfesion], [indicadorGenero], [indicadorEstado], [aceptaSMS], [telefonoMovil], [telefonoFijoCasa], [telefonoFijoTrabajo], [fechaDefuncion], [indicadorFallecido], [correo], [idBanco], [cuentaIBAN], [certificadoIBAN], [numeroVersionAuditoria], [fechaInsertoAuditoria], [idUsuarioInsertoAuditoria], [fechaModificoAuditoria], [idUsuarioModificoAuditoria]) VALUES (1925986, 1, N'303640366', N'JUAN PABLO', N'SOLANO', N'ALVARADO', CAST(N'1900-01-01T00:00:00.000' AS DateTime), NULL, 78, N'N.A.', NULL, 0, NULL, 0, 0, N'M', N'A', N'N', N'87858785', N'', N'', NULL, N'N', N'solanoaj@gmail.com', 23, N'CR85454545454454545454', NULL, 1, CAST(N'2023-12-11T15:14:58.777' AS DateTime), 3, NULL, NULL)
GO
INSERT [dbo].[SICORE_PERSONA] ([idPersona], [idTipoDocumentoID], [documentoID], [nombre], [primerApellido], [segundoApellido], [fechaNacimiento], [fechaCaducidadDocID], [idDistrito], [direccionExacta], [caserio], [idEstadoCivil], [apartadoPostal], [idGradoAcademico], [idProfesion], [indicadorGenero], [indicadorEstado], [aceptaSMS], [telefonoMovil], [telefonoFijoCasa], [telefonoFijoTrabajo], [fechaDefuncion], [indicadorFallecido], [correo], [idBanco], [cuentaIBAN], [certificadoIBAN], [numeroVersionAuditoria], [fechaInsertoAuditoria], [idUsuarioInsertoAuditoria], [fechaModificoAuditoria], [idUsuarioModificoAuditoria]) VALUES (1935259, 1, N'303740364', N'KAREN MARSELLA', N'NUÑEZ', N'SOLANO', CAST(N'1900-01-01T00:00:00.000' AS DateTime), NULL, 88, NULL, NULL, 0, NULL, 0, 0, N'F', N'A', N'N', N'88731021', NULL, NULL, NULL, N'N', N'karenuso@gmail.com', 1, N'CR22222222222222222222', NULL, 3, CAST(N'2023-11-17T09:57:39.073' AS DateTime), 0, CAST(N'2023-10-20T12:54:31.590' AS DateTime), 2216)
GO
INSERT [dbo].[SICORE_PERSONA] ([idPersona], [idTipoDocumentoID], [documentoID], [nombre], [primerApellido], [segundoApellido], [fechaNacimiento], [fechaCaducidadDocID], [idDistrito], [direccionExacta], [caserio], [idEstadoCivil], [apartadoPostal], [idGradoAcademico], [idProfesion], [indicadorGenero], [indicadorEstado], [aceptaSMS], [telefonoMovil], [telefonoFijoCasa], [telefonoFijoTrabajo], [fechaDefuncion], [indicadorFallecido], [correo], [idBanco], [cuentaIBAN], [certificadoIBAN], [numeroVersionAuditoria], [fechaInsertoAuditoria], [idUsuarioInsertoAuditoria], [fechaModificoAuditoria], [idUsuarioModificoAuditoria]) VALUES (2824708, 1, N'700510871', N'MIGUEL GERARDO', N'ARAYA', N'GONGORA', CAST(N'1900-01-01T00:00:00.000' AS DateTime), NULL, 67, N'N.A.dsfgsdf', N'ddfsfsddsf', 0, NULL, 0, 0, N'M', N'A', N'S', N'60178953', NULL, NULL, NULL, N'N', N'fdssdfas@gmail.com', NULL, NULL, NULL, 1, CAST(N'2023-12-11T14:43:16.183' AS DateTime), 3, NULL, NULL)
GO
INSERT [dbo].[SICORE_PERSONA] ([idPersona], [idTipoDocumentoID], [documentoID], [nombre], [primerApellido], [segundoApellido], [fechaNacimiento], [fechaCaducidadDocID], [idDistrito], [direccionExacta], [caserio], [idEstadoCivil], [apartadoPostal], [idGradoAcademico], [idProfesion], [indicadorGenero], [indicadorEstado], [aceptaSMS], [telefonoMovil], [telefonoFijoCasa], [telefonoFijoTrabajo], [fechaDefuncion], [indicadorFallecido], [correo], [idBanco], [cuentaIBAN], [certificadoIBAN], [numeroVersionAuditoria], [fechaInsertoAuditoria], [idUsuarioInsertoAuditoria], [fechaModificoAuditoria], [idUsuarioModificoAuditoria]) VALUES (2946804, 1, N'701960975', N'JOSE MIGUEL', N'ROJAS', N'ARGUELLO', CAST(N'1990-01-11T00:00:00.000' AS DateTime), NULL, 65, N'LIMON,POCOCI,GUAPILES,DEL CRUCE DE LA TROsdffdsCHA 400 OESTE SOBRE RUTA32.', N'fdsfsd', 1, NULL, 0, 21, N'M', N'A', N'S', N'60555555', NULL, NULL, NULL, N'N', N'dfasdfsda@gmail.com', NULL, NULL, NULL, NULL, CAST(N'2023-12-11T14:44:27.193' AS DateTime), 3, NULL, NULL)
GO
INSERT [dbo].[SICORE_PERSONA] ([idPersona], [idTipoDocumentoID], [documentoID], [nombre], [primerApellido], [segundoApellido], [fechaNacimiento], [fechaCaducidadDocID], [idDistrito], [direccionExacta], [caserio], [idEstadoCivil], [apartadoPostal], [idGradoAcademico], [idProfesion], [indicadorGenero], [indicadorEstado], [aceptaSMS], [telefonoMovil], [telefonoFijoCasa], [telefonoFijoTrabajo], [fechaDefuncion], [indicadorFallecido], [correo], [idBanco], [cuentaIBAN], [certificadoIBAN], [numeroVersionAuditoria], [fechaInsertoAuditoria], [idUsuarioInsertoAuditoria], [fechaModificoAuditoria], [idUsuarioModificoAuditoria]) VALUES (2946805, 1, N'701960976', N'BYRON ANDRE', N'RAMÍREZ', N'MORA', CAST(N'1900-01-01T00:00:00.000' AS DateTime), NULL, 68, N'12313', NULL, 0, NULL, 12, 60, N'M', N'A', N'N', N'8624319e', NULL, NULL, NULL, N'N', N'byron.ramirez@fonafifo.com', 1, NULL, NULL, 2, CAST(N'2023-11-13T07:42:29.493' AS DateTime), 3, CAST(N'2023-12-11T14:41:20.910' AS DateTime), 21)
GO
INSERT [dbo].[SICORE_PERSONA] ([idPersona], [idTipoDocumentoID], [documentoID], [nombre], [primerApellido], [segundoApellido], [fechaNacimiento], [fechaCaducidadDocID], [idDistrito], [direccionExacta], [caserio], [idEstadoCivil], [apartadoPostal], [idGradoAcademico], [idProfesion], [indicadorGenero], [indicadorEstado], [aceptaSMS], [telefonoMovil], [telefonoFijoCasa], [telefonoFijoTrabajo], [fechaDefuncion], [indicadorFallecido], [correo], [idBanco], [cuentaIBAN], [certificadoIBAN], [numeroVersionAuditoria], [fechaInsertoAuditoria], [idUsuarioInsertoAuditoria], [fechaModificoAuditoria], [idUsuarioModificoAuditoria]) VALUES (3033818, 1, N'800900496', N'BAYARDO JOSE', N'REYES', N'GUERRERO', CAST(N'1900-01-01T00:00:00.000' AS DateTime), NULL, 0, NULL, NULL, 0, NULL, 0, 0, N'M', N'A', NULL, N'77747474', NULL, NULL, NULL, NULL, N'bayardor@gmail.com', NULL, NULL, NULL, 1, CAST(N'2023-11-27T09:24:05.247' AS DateTime), 27, CAST(N'2023-11-27T09:24:05.247' AS DateTime), 27)
GO
INSERT [dbo].[SICORE_PERSONA] ([idPersona], [idTipoDocumentoID], [documentoID], [nombre], [primerApellido], [segundoApellido], [fechaNacimiento], [fechaCaducidadDocID], [idDistrito], [direccionExacta], [caserio], [idEstadoCivil], [apartadoPostal], [idGradoAcademico], [idProfesion], [indicadorGenero], [indicadorEstado], [aceptaSMS], [telefonoMovil], [telefonoFijoCasa], [telefonoFijoTrabajo], [fechaDefuncion], [indicadorFallecido], [correo], [idBanco], [cuentaIBAN], [certificadoIBAN], [numeroVersionAuditoria], [fechaInsertoAuditoria], [idUsuarioInsertoAuditoria], [fechaModificoAuditoria], [idUsuarioModificoAuditoria]) VALUES (3132577, 3, N'3101335313', N'DECO CREATIVA SOCIEDAD ANÓNIMA', N'', N'', CAST(N'1990-01-01T00:00:00.000' AS DateTime), NULL, 10500, N'SAN JOSE SANTA ANA, DETRAS DEL CENTRO COMERCIAL PLAZA ANTIGUA', NULL, 0, NULL, 0, 34, N'M', N'A', N'N', N'87128378', NULL, NULL, NULL, N'N', N'decocreativasa@gmail.com', 11, N'CR12222222222222222222', NULL, NULL, CAST(N'2023-11-27T08:01:19.940' AS DateTime), 3, CAST(N'2023-12-04T11:52:13.433' AS DateTime), NULL)
GO
INSERT [dbo].[SICORE_PERSONA] ([idPersona], [idTipoDocumentoID], [documentoID], [nombre], [primerApellido], [segundoApellido], [fechaNacimiento], [fechaCaducidadDocID], [idDistrito], [direccionExacta], [caserio], [idEstadoCivil], [apartadoPostal], [idGradoAcademico], [idProfesion], [indicadorGenero], [indicadorEstado], [aceptaSMS], [telefonoMovil], [telefonoFijoCasa], [telefonoFijoTrabajo], [fechaDefuncion], [indicadorFallecido], [correo], [idBanco], [cuentaIBAN], [certificadoIBAN], [numeroVersionAuditoria], [fechaInsertoAuditoria], [idUsuarioInsertoAuditoria], [fechaModificoAuditoria], [idUsuarioModificoAuditoria]) VALUES (3132585, 3, N'3101296147', N'AGRO CUATRO Y DOS J F C SOCIEDAD ANONIMA', N'', N'', CAST(N'1900-01-01T00:00:00.000' AS DateTime), NULL, 67, N'N.A.', NULL, 0, NULL, 0, 0, N'M', N'A', N'N', N'83097311', NULL, NULL, NULL, N'N', N'carolinachavezrodriguez@gmail.com', 2, N'CR89015202001125723656', NULL, 1, CAST(N'2023-12-07T14:21:14.083' AS DateTime), 3, NULL, NULL)
GO
INSERT [dbo].[SICORE_PERSONA] ([idPersona], [idTipoDocumentoID], [documentoID], [nombre], [primerApellido], [segundoApellido], [fechaNacimiento], [fechaCaducidadDocID], [idDistrito], [direccionExacta], [caserio], [idEstadoCivil], [apartadoPostal], [idGradoAcademico], [idProfesion], [indicadorGenero], [indicadorEstado], [aceptaSMS], [telefonoMovil], [telefonoFijoCasa], [telefonoFijoTrabajo], [fechaDefuncion], [indicadorFallecido], [correo], [idBanco], [cuentaIBAN], [certificadoIBAN], [numeroVersionAuditoria], [fechaInsertoAuditoria], [idUsuarioInsertoAuditoria], [fechaModificoAuditoria], [idUsuarioModificoAuditoria]) VALUES (3132588, 3, N'3101412288', N'RAYUELA OSA SOCIEDAD ANÓNIMA', N'', N'', CAST(N'1990-01-01T00:00:00.000' AS DateTime), NULL, 30, N'SJ ZAPOTE CARRETERA VIEJA A ZAPOTE DE RADIO COLUMBIA 100 N CONJUNTO DE 4 APARTAMENTOS A MANO DERECHA', NULL, 0, NULL, 0, 2, N'M', N'A', N'N', N'83753393', NULL, N'22837193', NULL, N'N', N'temp@temp.com', 20, N'CR98888888888888888888', NULL, NULL, CAST(N'2023-11-27T07:58:44.790' AS DateTime), 3, NULL, NULL)
GO
INSERT [dbo].[SICORE_PERSONA] ([idPersona], [idTipoDocumentoID], [documentoID], [nombre], [primerApellido], [segundoApellido], [fechaNacimiento], [fechaCaducidadDocID], [idDistrito], [direccionExacta], [caserio], [idEstadoCivil], [apartadoPostal], [idGradoAcademico], [idProfesion], [indicadorGenero], [indicadorEstado], [aceptaSMS], [telefonoMovil], [telefonoFijoCasa], [telefonoFijoTrabajo], [fechaDefuncion], [indicadorFallecido], [correo], [idBanco], [cuentaIBAN], [certificadoIBAN], [numeroVersionAuditoria], [fechaInsertoAuditoria], [idUsuarioInsertoAuditoria], [fechaModificoAuditoria], [idUsuarioModificoAuditoria]) VALUES (3132589, 3, N'3101214297', N'HAYMAX SOCIEDAD ANÓNIMA', N'', N'', CAST(N'1900-01-01T00:00:00.000' AS DateTime), NULL, 205, N'SAN JOSÉ  BARRIO  MEXICO DETRAS DE LA ESCUELA  COSTA RICA
', NULL, 0, NULL, 0, 2, N'M', N'A', N'N', N'78897897', N'22441303', NULL, NULL, N'N', N'gcarmiol@gmail.com', 11, N'CR33333333333333333333', NULL, NULL, CAST(N'2023-11-27T08:04:10.300' AS DateTime), 3, NULL, NULL)
GO
INSERT [dbo].[SICORE_PERSONA] ([idPersona], [idTipoDocumentoID], [documentoID], [nombre], [primerApellido], [segundoApellido], [fechaNacimiento], [fechaCaducidadDocID], [idDistrito], [direccionExacta], [caserio], [idEstadoCivil], [apartadoPostal], [idGradoAcademico], [idProfesion], [indicadorGenero], [indicadorEstado], [aceptaSMS], [telefonoMovil], [telefonoFijoCasa], [telefonoFijoTrabajo], [fechaDefuncion], [indicadorFallecido], [correo], [idBanco], [cuentaIBAN], [certificadoIBAN], [numeroVersionAuditoria], [fechaInsertoAuditoria], [idUsuarioInsertoAuditoria], [fechaModificoAuditoria], [idUsuarioModificoAuditoria]) VALUES (3132605, 3, N'3101219190', N'SOCIEDAD GANADERA LA CARMELA DEL POAS SOCIEDAD ANÓNIMA', N'', N'', CAST(N'1990-01-01T00:00:00.000' AS DateTime), NULL, 243, N'SAN RAFAEL  DE POAS ', NULL, 0, NULL, 0, 0, N'M', N'A', N'N', N'88458773', N'24822117', N'24822117', NULL, N'N', N'scgana@temp.com', 21, N'CR88015103310010015645', NULL, 1, CAST(N'2023-12-05T13:33:55.913' AS DateTime), 3, NULL, NULL)
GO
INSERT [dbo].[SICORE_PERSONA] ([idPersona], [idTipoDocumentoID], [documentoID], [nombre], [primerApellido], [segundoApellido], [fechaNacimiento], [fechaCaducidadDocID], [idDistrito], [direccionExacta], [caserio], [idEstadoCivil], [apartadoPostal], [idGradoAcademico], [idProfesion], [indicadorGenero], [indicadorEstado], [aceptaSMS], [telefonoMovil], [telefonoFijoCasa], [telefonoFijoTrabajo], [fechaDefuncion], [indicadorFallecido], [correo], [idBanco], [cuentaIBAN], [certificadoIBAN], [numeroVersionAuditoria], [fechaInsertoAuditoria], [idUsuarioInsertoAuditoria], [fechaModificoAuditoria], [idUsuarioModificoAuditoria]) VALUES (3132607, 3, N'3101663131', N'CORPORACION GAMMA DE CUTRIS SOCIEDAD ANONIMA', N'', N'', CAST(N'2015-01-12T00:00:00.000' AS DateTime), NULL, 77, N'ALAJUELA, SAN CARLOS, AGUAS ZARCAS', NULL, 0, NULL, 0, 0, N'M', N'A', N'S', N'89376602', NULL, NULL, NULL, N'N', N'humbertogamboa1949@gmail.com', 20, N'CR22222222222222222222', NULL, 1, CAST(N'2023-12-08T11:58:55.770' AS DateTime), 3, NULL, NULL)
GO
INSERT [dbo].[SICORE_PERSONA] ([idPersona], [idTipoDocumentoID], [documentoID], [nombre], [primerApellido], [segundoApellido], [fechaNacimiento], [fechaCaducidadDocID], [idDistrito], [direccionExacta], [caserio], [idEstadoCivil], [apartadoPostal], [idGradoAcademico], [idProfesion], [indicadorGenero], [indicadorEstado], [aceptaSMS], [telefonoMovil], [telefonoFijoCasa], [telefonoFijoTrabajo], [fechaDefuncion], [indicadorFallecido], [correo], [idBanco], [cuentaIBAN], [certificadoIBAN], [numeroVersionAuditoria], [fechaInsertoAuditoria], [idUsuarioInsertoAuditoria], [fechaModificoAuditoria], [idUsuarioModificoAuditoria]) VALUES (3132610, 3, N'3102663095', N'MTF TECA DE COSTA RICA. LTDA', N'', N'', CAST(N'1990-01-01T00:00:00.000' AS DateTime), NULL, 4, N'SAN JOSE, SAN JOSE, SABANA NORTE, EDIFICIO TORRE LA SABANA, 5 PISO, BUFETE PACHECO, ODIO Y ALFARO', NULL, 0, NULL, 0, 0, N'M', N'A', N'S', N'88543174', NULL, NULL, NULL, N'N', N'cristianv35@hotmail.com', 1, N'CR83015106910010016913', NULL, 1, CAST(N'2023-11-29T17:41:46.610' AS DateTime), 3, NULL, NULL)
GO
INSERT [dbo].[SICORE_PERSONA] ([idPersona], [idTipoDocumentoID], [documentoID], [nombre], [primerApellido], [segundoApellido], [fechaNacimiento], [fechaCaducidadDocID], [idDistrito], [direccionExacta], [caserio], [idEstadoCivil], [apartadoPostal], [idGradoAcademico], [idProfesion], [indicadorGenero], [indicadorEstado], [aceptaSMS], [telefonoMovil], [telefonoFijoCasa], [telefonoFijoTrabajo], [fechaDefuncion], [indicadorFallecido], [correo], [idBanco], [cuentaIBAN], [certificadoIBAN], [numeroVersionAuditoria], [fechaInsertoAuditoria], [idUsuarioInsertoAuditoria], [fechaModificoAuditoria], [idUsuarioModificoAuditoria]) VALUES (3132716, 3, N'3101192227', N'AGROPECUARIA EL METATE DEL NORTE SOCIEDAD ANÓNIMA', N'', N'', CAST(N'2015-01-12T00:00:00.000' AS DateTime), NULL, 194, N'300 METROS SUR DE LA ESCUELA DE LOS ALPES, VENECIA, SAN CARLOS', NULL, 0, NULL, 0, 0, N'M', N'A', N'S', N'83279702', N'24721367', NULL, NULL, N'N', N'laduanav@hotmail.com', 20, N'CR11111111111111111111', NULL, 2, CAST(N'2023-12-04T14:14:59.197' AS DateTime), 3, CAST(N'2023-12-05T09:41:31.690' AS DateTime), NULL)
GO
INSERT [dbo].[SICORE_PERSONA] ([idPersona], [idTipoDocumentoID], [documentoID], [nombre], [primerApellido], [segundoApellido], [fechaNacimiento], [fechaCaducidadDocID], [idDistrito], [direccionExacta], [caserio], [idEstadoCivil], [apartadoPostal], [idGradoAcademico], [idProfesion], [indicadorGenero], [indicadorEstado], [aceptaSMS], [telefonoMovil], [telefonoFijoCasa], [telefonoFijoTrabajo], [fechaDefuncion], [indicadorFallecido], [correo], [idBanco], [cuentaIBAN], [certificadoIBAN], [numeroVersionAuditoria], [fechaInsertoAuditoria], [idUsuarioInsertoAuditoria], [fechaModificoAuditoria], [idUsuarioModificoAuditoria]) VALUES (3208197, 3, N'3101419170', N'VIJUFER SOCIEDAD ANONIMA', N'', N'', CAST(N'1990-01-01T00:00:00.000' AS DateTime), NULL, 101, N'N.A.', NULL, 0, NULL, 0, 0, N'M', N'A', N'N', N'88888888', NULL, NULL, NULL, N'N', N'temp@tmp.tmp', 20, N'CR22222222222222222222', NULL, NULL, CAST(N'2023-11-27T10:18:58.037' AS DateTime), 27, NULL, NULL)
GO
INSERT [dbo].[SICORE_PERSONA] ([idPersona], [idTipoDocumentoID], [documentoID], [nombre], [primerApellido], [segundoApellido], [fechaNacimiento], [fechaCaducidadDocID], [idDistrito], [direccionExacta], [caserio], [idEstadoCivil], [apartadoPostal], [idGradoAcademico], [idProfesion], [indicadorGenero], [indicadorEstado], [aceptaSMS], [telefonoMovil], [telefonoFijoCasa], [telefonoFijoTrabajo], [fechaDefuncion], [indicadorFallecido], [correo], [idBanco], [cuentaIBAN], [certificadoIBAN], [numeroVersionAuditoria], [fechaInsertoAuditoria], [idUsuarioInsertoAuditoria], [fechaModificoAuditoria], [idUsuarioModificoAuditoria]) VALUES (3209937, 1, N'605110180', N'TATIANA', N'SOTO ', N'MOSQUERA', CAST(N'2008-04-03T00:00:00.000' AS DateTime), NULL, 76, N'N.A.', NULL, 0, NULL, 0, 0, N'F', N'A', N'S', N'88888888', NULL, NULL, NULL, N'N', N'prueba@prueba.com', 1, N'CR22222222222222222222', NULL, 1, CAST(N'2023-12-04T11:49:14.693' AS DateTime), 3, NULL, NULL)
GO
INSERT [dbo].[SICORE_PERSONA] ([idPersona], [idTipoDocumentoID], [documentoID], [nombre], [primerApellido], [segundoApellido], [fechaNacimiento], [fechaCaducidadDocID], [idDistrito], [direccionExacta], [caserio], [idEstadoCivil], [apartadoPostal], [idGradoAcademico], [idProfesion], [indicadorGenero], [indicadorEstado], [aceptaSMS], [telefonoMovil], [telefonoFijoCasa], [telefonoFijoTrabajo], [fechaDefuncion], [indicadorFallecido], [correo], [idBanco], [cuentaIBAN], [certificadoIBAN], [numeroVersionAuditoria], [fechaInsertoAuditoria], [idUsuarioInsertoAuditoria], [fechaModificoAuditoria], [idUsuarioModificoAuditoria]) VALUES (3867566, 1, N'801160615', N'JUAN                          ', N'PEREZ                     ', N'DE LA CRUZ                ', CAST(N'1900-01-01T00:00:00.000' AS DateTime), NULL, 0, NULL, NULL, 0, NULL, 0, 0, N'M', N'A', NULL, N'85758576', NULL, NULL, NULL, NULL, N'juan.perez@temporal.temp', NULL, NULL, NULL, 2, CAST(N'2023-10-17T11:40:44.823' AS DateTime), 12, CAST(N'2023-10-24T15:49:00.477' AS DateTime), 5)
GO
SET IDENTITY_INSERT [dbo].[SICORE_USUARIO] ON 
GO
INSERT [dbo].[SICORE_USUARIO] ([idUsuario], [idPersona], [idPerfil], [idSubOficinaRegional], [usuario], [clave], [indicadorEstado], [fechaVenceClave], [numeroVersionAuditoria], [fechaInsertoAuditoria], [idUsuarioInsertoAuditoria], [fechaModificoAuditoria], [idUsuarioModificoAuditoria], [ultimoAcceso], [claveTemporal], [claveB], [imgFirma]) VALUES (3, 1935259, 1, NULL, N'karenuso@gmail.com', N'1/2%4-5', N'A', CAST(N'2024-03-27T11:31:12.747' AS DateTime), 1, CAST(N'2023-10-12T10:02:58.397' AS DateTime), 1, CAST(N'2023-11-17T08:16:16.543' AS DateTime), 3, CAST(N'2024-02-26' AS Date), N'N', 0x41334641367E33323144256362617E3334353631363138330000000000000000000000000000000000000000000000000000, NULL)
GO
INSERT [dbo].[SICORE_USUARIO] ([idUsuario], [idPersona], [idPerfil], [idSubOficinaRegional], [usuario], [clave], [indicadorEstado], [fechaVenceClave], [numeroVersionAuditoria], [fechaInsertoAuditoria], [idUsuarioInsertoAuditoria], [fechaModificoAuditoria], [idUsuarioModificoAuditoria], [ultimoAcceso], [claveTemporal], [claveB], [imgFirma]) VALUES (5, 555239, 2, NULL, N'cdiaz@fonafifo.go.cr', NULL, N'A', CAST(N'2024-03-27T11:31:12.747' AS DateTime), 1, CAST(N'2023-10-12T10:00:00.000' AS DateTime), 1, CAST(N'2023-10-12T10:00:00.000' AS DateTime), 1, CAST(N'2024-02-26' AS Date), N'N', NULL, NULL)
GO
INSERT [dbo].[SICORE_USUARIO] ([idUsuario], [idPersona], [idPerfil], [idSubOficinaRegional], [usuario], [clave], [indicadorEstado], [fechaVenceClave], [numeroVersionAuditoria], [fechaInsertoAuditoria], [idUsuarioInsertoAuditoria], [fechaModificoAuditoria], [idUsuarioModificoAuditoria], [ultimoAcceso], [claveTemporal], [claveB], [imgFirma]) VALUES (6, 857004, 5, NULL, N'jespinoza@fonafifo.go.cr', N'1/2%4-5', N'A', CAST(N'2024-03-27T11:31:12.747' AS DateTime), 1, CAST(N'2023-10-13T10:10:52.890' AS DateTime), 5, CAST(N'2023-10-13T10:10:52.890' AS DateTime), 5, CAST(N'2024-02-26' AS Date), N'N', 0x33363146387E4644393433447E39393130373130350000000000000000000000000000000000000000000000000000000000, N'firmajespinoza.jpg')
GO
INSERT [dbo].[SICORE_USUARIO] ([idUsuario], [idPersona], [idPerfil], [idSubOficinaRegional], [usuario], [clave], [indicadorEstado], [fechaVenceClave], [numeroVersionAuditoria], [fechaInsertoAuditoria], [idUsuarioInsertoAuditoria], [fechaModificoAuditoria], [idUsuarioModificoAuditoria], [ultimoAcceso], [claveTemporal], [claveB], [imgFirma]) VALUES (12, 3867566, 1, NULL, N'juan.perez@temp.temp', N'1/2%4-5', N'A', CAST(N'2024-03-27T11:31:12.747' AS DateTime), 1, CAST(N'2023-10-17T11:40:44.823' AS DateTime), 1, CAST(N'2023-10-17T11:40:44.823' AS DateTime), 1, CAST(N'2024-02-26' AS Date), N'N', 0x45433631467E3433323144256362617E33333233303739373700000000000000000000000000000000000000000000000000, NULL)
GO
INSERT [dbo].[SICORE_USUARIO] ([idUsuario], [idPersona], [idPerfil], [idSubOficinaRegional], [usuario], [clave], [indicadorEstado], [fechaVenceClave], [numeroVersionAuditoria], [fechaInsertoAuditoria], [idUsuarioInsertoAuditoria], [fechaModificoAuditoria], [idUsuarioModificoAuditoria], [ultimoAcceso], [claveTemporal], [claveB], [imgFirma]) VALUES (14, 818796, 3, NULL, N'cbaltodano@fonafifo.go.cr', N'1/2%4-5', N'A', CAST(N'2024-03-27T11:31:12.747' AS DateTime), 2, CAST(N'2023-10-20T10:29:46.833' AS DateTime), 2216, CAST(N'2023-10-23T10:45:21.080' AS DateTime), 2216, CAST(N'2024-02-26' AS Date), N'N', NULL, NULL)
GO
INSERT [dbo].[SICORE_USUARIO] ([idUsuario], [idPersona], [idPerfil], [idSubOficinaRegional], [usuario], [clave], [indicadorEstado], [fechaVenceClave], [numeroVersionAuditoria], [fechaInsertoAuditoria], [idUsuarioInsertoAuditoria], [fechaModificoAuditoria], [idUsuarioModificoAuditoria], [ultimoAcceso], [claveTemporal], [claveB], [imgFirma]) VALUES (17, 2888867, 5, NULL, N'vsamuels@fonafifo.go.cr', N'1/2%4-5', N'A', CAST(N'2024-03-27T11:31:12.747' AS DateTime), 1, CAST(N'2023-10-23T11:13:49.687' AS DateTime), 2216, CAST(N'2023-10-23T11:13:49.687' AS DateTime), 2216, CAST(N'2024-02-26' AS Date), N'N', NULL, NULL)
GO
INSERT [dbo].[SICORE_USUARIO] ([idUsuario], [idPersona], [idPerfil], [idSubOficinaRegional], [usuario], [clave], [indicadorEstado], [fechaVenceClave], [numeroVersionAuditoria], [fechaInsertoAuditoria], [idUsuarioInsertoAuditoria], [fechaModificoAuditoria], [idUsuarioModificoAuditoria], [ultimoAcceso], [claveTemporal], [claveB], [imgFirma]) VALUES (18, 368512, 9, NULL, N'mlacayo@fonafifo.go.cr', N'1/2%4-5', N'A', CAST(N'2024-03-27T11:31:12.747' AS DateTime), 1, CAST(N'2023-10-30T11:20:20.040' AS DateTime), 5, CAST(N'2023-10-30T11:20:20.040' AS DateTime), 5, CAST(N'2024-02-26' AS Date), N'N', NULL, NULL)
GO
INSERT [dbo].[SICORE_USUARIO] ([idUsuario], [idPersona], [idPerfil], [idSubOficinaRegional], [usuario], [clave], [indicadorEstado], [fechaVenceClave], [numeroVersionAuditoria], [fechaInsertoAuditoria], [idUsuarioInsertoAuditoria], [fechaModificoAuditoria], [idUsuarioModificoAuditoria], [ultimoAcceso], [claveTemporal], [claveB], [imgFirma]) VALUES (22, 2946805, 1, NULL, N'byron.info@gmail.com', N'1/2%4-5', N'A', CAST(N'2024-03-27T11:31:12.747' AS DateTime), 1, CAST(N'2023-11-13T07:49:30.520' AS DateTime), 1, CAST(N'2023-11-13T07:49:30.520' AS DateTime), 1, CAST(N'2024-02-26' AS Date), N'N', 0x38413731437E3433323165646E61626F72507E32373938363237350000000000000000000000000000000000000000000000, NULL)
GO
INSERT [dbo].[SICORE_USUARIO] ([idUsuario], [idPersona], [idPerfil], [idSubOficinaRegional], [usuario], [clave], [indicadorEstado], [fechaVenceClave], [numeroVersionAuditoria], [fechaInsertoAuditoria], [idUsuarioInsertoAuditoria], [fechaModificoAuditoria], [idUsuarioModificoAuditoria], [ultimoAcceso], [claveTemporal], [claveB], [imgFirma]) VALUES (23, 2946805, 1, NULL, N'fsdfsadfa.fdasfdsafsa', N'1/2%4-5', N'A', CAST(N'2024-03-27T11:31:12.747' AS DateTime), 1, CAST(N'2023-11-13T08:31:27.313' AS DateTime), 1, CAST(N'2023-11-13T08:31:27.313' AS DateTime), 1, CAST(N'2024-02-26' AS Date), N'N', 0x34344433377E363534363534736166616473666473617E333136363638313835000000000000000000000000000000000000, NULL)
GO
INSERT [dbo].[SICORE_USUARIO] ([idUsuario], [idPersona], [idPerfil], [idSubOficinaRegional], [usuario], [clave], [indicadorEstado], [fechaVenceClave], [numeroVersionAuditoria], [fechaInsertoAuditoria], [idUsuarioInsertoAuditoria], [fechaModificoAuditoria], [idUsuarioModificoAuditoria], [ultimoAcceso], [claveTemporal], [claveB], [imgFirma]) VALUES (25, 555239, 1, NULL, N'cristiandiazcliente@temp.temp', N'1/2%4-5', N'A', CAST(N'2024-03-27T11:31:12.747' AS DateTime), 1, CAST(N'2023-11-17T10:48:49.620' AS DateTime), 1, CAST(N'2023-11-17T10:48:49.620' AS DateTime), 1, CAST(N'2024-02-26' AS Date), N'N', 0x33374643457E3132333444256362617E32373530333634300000000000000000000000000000000000000000000000000000, NULL)
GO
INSERT [dbo].[SICORE_USUARIO] ([idUsuario], [idPersona], [idPerfil], [idSubOficinaRegional], [usuario], [clave], [indicadorEstado], [fechaVenceClave], [numeroVersionAuditoria], [fechaInsertoAuditoria], [idUsuarioInsertoAuditoria], [fechaModificoAuditoria], [idUsuarioModificoAuditoria], [ultimoAcceso], [claveTemporal], [claveB], [imgFirma]) VALUES (27, 3033818, 1, NULL, N'bayardor@gmail.com', N'1/2%4-5', N'A', CAST(N'2024-03-27T11:31:12.747' AS DateTime), 1, CAST(N'2023-11-27T09:24:05.247' AS DateTime), 1, CAST(N'2023-11-30T08:54:07.970' AS DateTime), 27, CAST(N'2024-02-26' AS Date), N'N', 0x46354236377E62373635343332317E3739373034363037000000000000000000000000000000000000000000000000000000, NULL)
GO
SET IDENTITY_INSERT [dbo].[SICORE_USUARIO] OFF
GO
